// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVzpZYA7lRjvLNft4FWwy5RpJ0t5PfW4',
    appId: '1:312185918341:web:8cf7f575a1630521662aec',
    messagingSenderId: '312185918341',
    projectId: 'fmulti-stg',
    authDomain: 'fmulti-stg.firebaseapp.com',
    storageBucket: 'fmulti-stg.appspot.com',
    measurementId: 'G-KDN14MGSE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD872bvYXcewR1xt8P_glkzaUZ88FP3Tpw',
    appId: '1:312185918341:android:0b39b1d8808ae565662aec',
    messagingSenderId: '312185918341',
    projectId: 'fmulti-stg',
    storageBucket: 'fmulti-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiU4pACg9CR6LomSoewQLczsTDJxagcg',
    appId: '1:312185918341:ios:3bb450b06950cbeb662aec',
    messagingSenderId: '312185918341',
    projectId: 'fmulti-stg',
    storageBucket: 'fmulti-stg.appspot.com',
    iosBundleId: 'com.example.multiFirebaseProjectFlavors.stg',
  );
}
